# Generated by Django 5.0.2 on 2024-02-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_music', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='music_mp3/')),
                ('image_music', models.ImageField(blank=True, default='/home/yimanbek/Desktop/project_mp3/music/defaul_image/sEZB30zciy5YEGCrSUPkhKNMjcXUm7YdvC0PwpwIYZ3CRmhrXUDBnGwbKnN-ya9Z4VSnrqwe.jpg', upload_to='music_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='category.category')),
                ('in_albums', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music', to='albums.albums')),
            ],
        ),
    ]
