# Generated by Django 5.0.1 on 2024-02-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='author',
            new_name='username',
        ),
    ]
