# Generated by Django 5.0.1 on 2024-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_email_music_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_text',
            field=models.TextField(default=False),
        ),
    ]
