# Generated by Django 5.0.1 on 2024-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_music_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_music',
            field=models.ImageField(blank=True, upload_to='music_images/'),
        ),
    ]
