# Generated by Django 5.0.1 on 2024-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_music_image_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_music',
            field=models.ImageField(blank=True, default='/home/yimanbek/Desktop/project_mp3/music/defaul_image/sEZB30zciy5YEGCrSUPkhKNMjcXUm7YdvC0PwpwIYZ3CRmhrXUDBnGwbKnN-ya9Z4VSnrqwe.jpg', upload_to='music_images/'),
        ),
    ]
