# Generated by Django 5.0.1 on 2024-02-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0004_rename_email_music_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('musiс', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.music')),
            ],
        ),
    ]
