# Generated by Django 5.0.1 on 2024-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_remove_rating_value_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='musiс',
            new_name='music',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
