# Generated by Django 5.0.1 on 2024-02-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_remove_rating_value_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='value',
        ),
    ]
