# Generated by Django 5.0.1 on 2024-02-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_music_comment_name_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name_music',
            new_name='music',
        ),
    ]
